### ISSUE TITLE
userTerm is unknown

### ISSUE THREAD

**Issue by geektortoise** [Cytomine-ULiege/Cytomine-project-migrator#3]
Hello, 
thanks for this very useful tool.

I had a problem during the export made based on your Docker image.
In the step 4.2, it seems that the userTerm is not associated to the annotation object.

https://github.com/Cytomine-ULiege/Cytomine-project-migrator/blob/master/cytomineprojectmigrator/exporter.py#L163

I commented that part and it worked but maybe a flag is missing ?

**Comment by urubens** [comment]
Fixed by #10
